[project]
name = "user"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sanjayraj18", email = "22bsm052@iiitdmj.ac.in" }
]
requires-python = ">=3.9"
dependencies = [
    "bcrypt>=4.0.1,<4.1",
    "fastapi[standard]>=0.128.8",
    "passlib>=1.7.4",
]

[project.scripts]
user = "user:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
